apiVersion: v1
kind: Service
metadata:
  namespace: eloy-app
  name: back-lb-eloy-app
  labels:
    app: eloy-app
spec:
  selector:
    app: eloy-app-server
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer