apiVersion: v1
kind: Service
metadata:
  labels:
    app: eloy-app-server
  name: nodeport-service-server
  namespace: eloy-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5005
      nodePort: 30009
  selector:
    app: eloy-app-server