apiVersion: v1
kind: Service
metadata:
  labels:
    app: eloy-app-client
  name: nodeport-service-client
  namespace: eloy-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5173
      nodePort: 30008
  selector:
    app: eloy-app-client 