apiVersion: v1
kind: Service
metadata:
  name: nodeport-serice
  label:
    app: nodeport-service
spec:
  type: nodeport
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30008
  selector:
    app: sample-node-app 